### PR TITLE
fix tftpl variable parsing and remove unused variable

### PR DESCRIPTION
**Pull request by rizkimhd**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Fixes #0000

***

Release note for [CHANGELOG](https://github.com/traveloka/terraform-aws-bake-ami/blob/master/CHANGELOG.md):

```release-note
NOTES:

* Any Notes regarding your submitted PR, like breaking changes or else.

FEATURES:

* **New Source:** `aws_000_0000` ([#references_to_issue](./))

ENHANCEMENTS:

* feature: Add support for new version of AWS API

BUG FIXES:
* Fixing error AMI NAME due to the incorrect variable passing into the `*.tftpl`
```
[Container] 2022/09/26 08:13:10 Running command packer validate -var-file="packer_variables.json" /root/aws-ebs-traveloka-ansible.json
Error: Failed to prepare build: "amazon-ebs"
1 error(s) occurred:
* AMIName should only contain alphanumeric characters, parentheses (()), square brackets ([]), spaces ( ), periods (.), slashes (/), dashes (-), single quotes ('), at-signs (@), or underscores(_). You can use the `clean_resource_name` template filter to automatically clean your ami name.
```

* Prevent error from evil bugs
```

***

Output from `terraform plan` command from changes you propose.

```
$ terraform plan

```

### CODE REVIEW

**Comment by rizkimhd** [comment]
related error message:
```
[Container] 2022/09/26 08:13:10 Running command packer validate -var-file="packer_variables.json" /root/aws-ebs-traveloka-ansible.json
Error: Failed to prepare build: "amazon-ebs"
1 error(s) occurred:
* AMIName should only contain alphanumeric characters, parentheses (()), square brackets ([]), spaces ( ), periods (.), slashes (/), dashes (-), single quotes ('), at-signs (@), or underscores(_). You can use the `clean_resource_name` template filter to automatically clean your ami name.
```

**Comment by rizkimhd** [comment]
Before (buildspec from codebuild retrieved via aws console):
```
version: 0.2
env:
  variables:
    USER: "ubuntu"
    PACKER_NO_COLOR: "true"
    APP_TEMPLATE_SG_ID: "${template_instance_sg}"
    APP_TEMPLATE_INSTANCE_PROFILE: "${template_instance_profile}"
    APP_TEMPLATE_INSTANCE_VPC_ID: "${vpc_id}"
    APP_TEMPLATE_INSTANCE_SUBNET_ID: "${subnet_id}"
    AMI_NAME_PREFIX: "${app_ami_prefix}"
    STACK_AMI_OWNERS: "${base_ami_owners}"
    STACK_AMI_NAME_FILTER: "${base_ami_prefix}"
phases:
  pre_build:
    commands:
      - ansible-galaxy install -r requirements.yml
      - packer validate -var-file="packer_variables.json" /root/aws-ebs-traveloka-ansible.json
  build:
    commands:
      - packer build -var-file="packer_variables.json" /root/aws-ebs-traveloka-ansible.json
  post_build:
    commands:
      - IMAGE_KEY=$(jq -r ".builds[0].artifact_id" packer-manifest.json | sed -e "s#:#/#g")
      - jq --arg image_key "$IMAGE_KEY" '.[0].builds[0] as $pm | .[1] | .deployment += {"packerManifest":$pm} | .image = $image_key' -s packer-manifest.json gradle_manifest.json > build_manifest.json  || touch build_manifest.json
      - aws s3 cp build_manifest.json s3://${ami_baking_artifact_bucket}/$IMAGE_KEY/build_manifest.json --sse AES256
artifacts:
  secondary-artifacts:
    PackerManifest:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - packer-manifest.json
    BuildManifest:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - build_manifest.json
```

**Comment by rizkimhd** [comment]
After (buildspec from codebuild retrieved via aws console):
```
version: 0.2
env:
  variables:
    USER: "ubuntu"
    PACKER_NO_COLOR: "true"
    APP_TEMPLATE_SG_ID: "sg-0976f93ef1f027ab1"
    APP_TEMPLATE_INSTANCE_PROFILE: "InstanceProfile_acd-template-c67256bfb3eac5cd"
    APP_TEMPLATE_INSTANCE_VPC_ID: "vpc-073bcad888187176b"
    APP_TEMPLATE_INSTANCE_SUBNET_ID: "subnet-03e4dd7c4244c7e70"
    AMI_NAME_PREFIX: "tvlk/ubuntu-20/acd/java-11-"
    STACK_AMI_OWNERS: "460124681500,745412875337"
    STACK_AMI_NAME_FILTER: "tvlk/ubuntu-20/tsi/java-11/hvm/x86_64/*"
phases:
  pre_build:
    commands:
      - ansible-galaxy install -r requirements.yml
      - packer validate -var-file="packer_variables.json" /root/aws-ebs-traveloka-ansible.json
  build:
    commands:
      - packer build -var-file="packer_variables.json" /root/aws-ebs-traveloka-ansible.json
  post_build:
    commands:
      - IMAGE_KEY=$(jq -r ".builds[0].artifact_id" packer-manifest.json | sed -e "s#:#/#g")
      - jq --arg image_key "$IMAGE_KEY" '.[0].builds[0] as $pm | .[1] | .deployment += {"packerManifest":$pm} | .image = $image_key' -s packer-manifest.json gradle_manifest.json > build_manifest.json  || touch build_manifest.json
      - aws s3 cp build_manifest.json s3://acd-eng-manifest-874193996617ead57866c3ca0dd6/$IMAGE_KEY/build_manifest.json --sse AES256
artifacts:
  secondary-artifacts:
    PackerManifest:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - packer-manifest.json
    BuildManifest:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - build_manifest.json
```

**Review by ronny-kaluge — APPROVED** [review]
Thank you Rizki

**Pull request merged**
